; Yellow Racer - ESP32-2432S028R (Cheap Yellow Display / CYD)
; Board ID "esp32-2432S028" non esiste in PlatformIO -> si usa esp32dev
[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    paulstoffregen/XPT2046_Touchscreen
build_flags =
    -D USER_SETUP_LOADED=1
    -include src/User_Setup.h
